#pragma once
#include "Fullscreen.slangh"

float4 SmaaPoint(Texture2D<float4> Texture, float2 UV)
{
    uint W, H;
    Texture.GetDimensions(W, H);
    return Texture.Load(int3(clamp(int2(floor(UV * float2(W, H))), int2(0, 0), int2(W, H) - 1), 0));
}
#define SMAA_CUSTOM_SL 1
#define SMAA_RT_METRICS Visual.Viewport
#define SMAA_THRESHOLD Visual.Material.BaseColor.x
#define SMAA_MAX_SEARCH_STEPS int(Visual.Material.TextureFlags.y)
#define SMAA_MAX_SEARCH_STEPS_DIAG int(Visual.Material.TextureFlags.z)
#define SMAA_CORNER_ROUNDING Visual.Material.TextureFlags.w
#define SMAATexture2D(tex) Texture2D<float4> tex
#define SMAATexturePass2D(tex) tex
#define SMAASampleLevelZero(tex, coord) tex.SampleLevel(LinearSampler, coord, 0)
#define SMAASampleLevelZeroPoint(tex, coord) SmaaPoint(tex, coord)
#define SMAASampleLevelZeroOffset(tex, coord, offset) tex.SampleLevel(LinearSampler, coord + offset * Visual.Viewport.xy, 0)
#ifndef SMAASample
#define SMAASample(tex, coord) tex.SampleLevel(LinearSampler, coord, 0)
#endif
#ifndef SMAASamplePoint
#define SMAASamplePoint(tex, coord) SmaaPoint(tex, coord)
#endif
#ifndef SMAASampleOffset
#define SMAASampleOffset(tex, coord, offset) tex.SampleLevel(LinearSampler, coord + offset * Visual.Viewport.xy, 0)
#endif
#define SMAA_FLATTEN
#define SMAA_BRANCH
#define SMAATexture2DMS2(tex) Texture2DMS<float4, 2> tex
#define SMAALoad(tex, pos, sample) tex.Load(pos, sample)
#include "../../External/smaa/SMAA.hlsl"
